postman_job:
  image: "alpine:3.10"
  script: 
    - "npm install newman -g"
    - "newman run ${POSTMAN_COLLECTION} -e ${POSTMAN_ENVIRONMENT}"
  stage: postman
stages: 
  - some_stages
  - postman
variables: 
  POSTMAN_COLLECTION: postman_collection.json
  POSTMAN_ENVIRONMENT: postman_environment.json



  
  
  