postman_job:
  image: "alpine:3.10"
  script: 
    # - "npm install newman -g"
    - RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
    - RUN apt-get update
    - RUN apt-get -y install python-software-properties git build-essential
    - RUN add-apt-repository -y ppa:chris-lea/node.js
    - RUN apt-get update
    - RUN apt-get -y install nodejs
    - "newman run ${POSTMAN_COLLECTION} -e ${POSTMAN_ENVIRONMENT}"
  stage: postman
stages: 
  - some_stages
  - postman
variables: 
  POSTMAN_COLLECTION: postman_collection.json
  POSTMAN_ENVIRONMENT: postman_environment.json



  
  
  