postman_job: 
  before_script:
  - apt-get update -qq && apt-get install -y -qq curl
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y nodejs
  - npm install newman -g
  script: 
    - "newman run ${POSTMAN_COLLECTION} -e ${POSTMAN_ENVIRONMENT}"
  stage: postman
stages: 
  - some_stages
  - postman
variables: 
  POSTMAN_COLLECTION: postman_collection.json
  POSTMAN_ENVIRONMENT: postman_environment.json
